name: ESLint

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      src_path:
        required: false
        type: string
        default: 'src'

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Run ESLint
        run: npx eslint --no-error-on-unmatched-pattern ${{ inputs.src_path }}
